title: NCI Systems Status Page
languageCode: en
params:
  copyrightHolder: National Captioning Institute.
  dateFormat: 'January 2, 2006 at 15:00'
  description_footer: ' '
  description_header: ''
  eventsPerPage: 10
  groups:
    - ''
  logo: /images/clearstatus.svg
  meta_description: >-
    NCI system status page which provides updated information about operations
    status, incidents and their resolution.
  shortDateFormat: 'Jan 2 -- 15:04'
  systems:
    - description: VA (Virginia) VPN Server
      link: ''
      name: VPN - VA
    - description: RM (Remote) VPN Server
      link: ''
      name: VPN - RM
    - description: CA (California) VPN
      name: VPN - CA
    - description: >-
        CATO VPN - NCI's new SD-WAN VPN.  Configuration / Testing / Beta Release
        began in Nov 2019.
      name: VPN - CATO
    - description: CA (California) CCP Server
      name: CCP - CA
    - description: RM (Remote) CCP Server
      name: CCP - RM
    - description: VA (Virginia) CCP Server
      name: CCP - VA
    - description: Joblink - English
      link: ''
      name: Joblink
    - description: Joblink Notifier (Robocalls)
      name: Joblink Notifier
    - description: Joblink - Spanish
      name: Joblink - ES
    - description: 'EEG''s iCap Status Page, provided by EEG'
      link: 'https://status.icap.eegcloud.tv/'
      name: iCap Status
    - description: 'Office 365 Portal Status Page, provide by Microsoft'
      link: 'https://portal.office.com/servicestatus'
      name: Office 365 Portal Status
  timezoneString: EST
