title: NCI Systems Status Page
languageCode: en
params:
  copyrightHolder: National Captioning Institute.
  dateFormat: 'January 2, 2006 at 15:00'
  description_footer: ' '
  description_header: ''
  eventsPerPage: 10
  groups:
    - VPN Servers
    - CCP Servers
    - Joblink Resources
    - Reports
    - 3rd Party Status Pages
    - File Sharing Services
    - Decomissioned
  logo: /images/clearstatus.svg
  meta_description: >-
    NCI system status page which provides updated information about operations
    status, incidents and their resolution.
  shortDateFormat: 'Jan 2 -- 15:04'
  systems:
    - description: VA (Virginia) VPN Server
      group: VPN Servers
      link: ''
      name: VPN - VA
    - description: RM (Remote) VPN Server
      group: VPN Servers
      link: ''
      name: VPN - RM
    - description: CA (California) VPN
      group: VPN Servers
      name: VPN - CA
    - description: >-
        CATO VPN - NCI's new SD-WAN VPN.  Configuration / Testing / Beta Release
        began in Nov 2019.
      group: VPN Servers
      name: VPN - CATO
    - description: CA (California) CCP Server
      group: CCP Servers
      name: CCP - CA
    - description: RM (Remote) CCP Server
      group: CCP Servers
      name: CCP - RM
    - description: VA (Virginia) CCP Server
      group: CCP Servers
      name: CCP - VA
    - description: Joblink - English
      group: Joblink Resources
      link: ''
      name: Joblink
    - description: Joblink Notifier (Robocalls)
      group: Joblink Resources
      name: Joblink Notifier
    - description: Joblink - Spanish
      group: Joblink Resources
      name: Joblink - ES
    - description: 'EEG''s iCap Status Page, provided by EEG'
      group: 3rd Party Status Pages
      link: 'https://status.icap.eegcloud.tv/'
      name: iCap Status
    - description: 'Office 365 Portal Status Page, provide by Microsoft'
      group: 3rd Party Status Pages
      link: 'https://portal.office.com/servicestatus'
      name: Office 365 Portal Status
    - description: 'Joblink backup schedules mailed 2x daily, 6:00 and 18:00'
      group: Reports
      name: Joblink Backup Schedules
    - description: Monthly Program Ending Reports mailed to Marketing monthly
      group: Reports
      name: Joblink Program Ending Report
    - description: 'Sharefile System Status page, provided by Citrix'
      group: 3rd Party Status Pages
      link: 'http://status.sharefile.com/'
      name: Sharefile System Status
    - description: FTP Server used for file exchange with clients
      group: Decomissioned
      name: FTP Server
    - description: Sharefile SaaS Service used to exchange files with clients
      group: File Sharing Services
      link: 'https://ncicap.sharefile.com'
      name: Sharefile Service
  timezoneString: EST
