title: NCI Systems Status Page
languageCode: en
params:
  copyrightHolder: National Captioning Institute.
  dateFormat: 'January 2, 2006 at 15:00'
  description_footer: ''
  description_header: ''
  eventsPerPage: 10
  groups:
    - ''
  logo: /images/logo.png
  meta_description: >-
    NCI system status page which provides updated information about operations
    status, incidents and their resolution.
  shortDateFormat: 'Jan 2 -- 15:04'
  systems:
    - description: VA (Virginia) VPN Server
      group: VLAN
      link: ''
      name: VA VPN
    - description: RM (Remote) VPN Server
      group: VLAN
      link: ''
      name: RM VPN
    - description: CA (California) VPN
      group: VLAN
      name: CA VPN
    - description: >-
        CATO VPN - NCI's new SD-WAN VPN.  Configuration / Testing / Beta Release
        began in Nov 2019.
      group: VLAN
      name: CATO VON
    - description: CA (California) CCP
      name: CCP - CA
  timezoneString: EST
