title: NCI Systems Status Page
languageCode: en
params:
  copyrightHolder: National Captioning Institute.
  dateFormat: 'January 2, 2006 at 15:00'
  description_footer: ''
  description_header: >-
    Better systems status communication.  This page provides information about
    operations status, incidents, and their resolution.
  eventsPerPage: 10
  groups:
    - VLAN
  logo: /images/logo.jpg
  meta_description: >-
    NCI system status page which provides updated information about operations
    status, incidents and their resolution.
  shortDateFormat: 'Jan 2 -- 15:04'
  systems:
    - description: VA (Virginia) VPN Server
      link: ''
      name: VA VPN
    - description: RM (Remote) VPN Server
      link: ''
      name: RM VPN
    - description: CA (California) VPN
      name: CA VPN
    - description: >-
        CATO VPN - NCI's new SD-WAN VPN.  Configuration / Testing / Beta Release
        began in Nov 2019.
      name: CATO VON
  timezoneString: EST
