title: NCI Systems Status Page
languageCode: en
params:
  copyrightHolder: National Captioning Institute.
  dateFormat: 'January 2, 2006 at 15:00'
  description_footer: ' '
  description_header: ''
  eventsPerPage: 10
  groups:
    - Accounting
    - CapNET Resources
    - CaptionSentry Servers
    - CCP Servers
    - Decomissioned
    - Domain Controllers
    - File Sharing Services
    - Joblink Resources
    - Management Servers
    - Reports
    - VPN Servers
    - 3rd Party Status Pages
  logo: /images/clearstatus.svg
  meta_description: >-
    NCI system status page which provides updated information about operations
    status, incidents and their resolution.
  shortDateFormat: 'Jan 2 -- 15:04'
  systems:
    - description: CA (California) VPN
      group: VPN Servers
      name: VPN - CA
    - description: >-
        CATO VPN - NCI's new SD-WAN VPN.  Configuration / Testing / Beta Release
        began in Nov 2019.
      group: VPN Servers
      name: VPN - CATO
    - description: RM (Remote) VPN Server
      group: VPN Servers
      link: ''
      name: VPN - RM
    - description: VA (Virginia) VPN Server
      group: VPN Servers
      link: ''
      name: VPN - VA
    - description: CA (California) CCP Server
      group: CCP Servers
      name: CCP - CA
    - description: RM (Remote) CCP Server
      group: CCP Servers
      name: CCP - RM
    - description: VA (Virginia) CCP Server
      group: CCP Servers
      name: CCP - VA
    - description: Joblink - English
      group: Joblink Resources
      link: ''
      name: Joblink
    - description: Joblink - Spanish
      group: Joblink Resources
      name: Joblink - ES
    - description: Joblink DB
      group: Joblink Resources
      name: Joblink DB
    - description: Joblink Notifier (Robocalls)
      group: Joblink Resources
      name: Joblink Notifier
    - description: 'EEG''s iCap Status Page, provided by EEG'
      group: 3rd Party Status Pages
      link: 'https://status.icap.eegcloud.tv/'
      name: iCap Status
    - description: 'Office 365 Portal Status Page, provide by Microsoft'
      group: 3rd Party Status Pages
      link: 'https://portal.office.com/servicestatus'
      name: Office 365 Portal Status
    - description: 'Joblink backup schedules mailed 2x daily, 6:00 and 18:00'
      group: Reports
      name: 'RPT - Backup Schedules, Joblink'
    - description: Monthly Program Ending Reports mailed to Marketing monthly
      group: Reports
      name: 'RPT- Program Ending, Joblink'
    - description: Network j-drive files
      group: File Sharing Services
      name: Network Group Drive Files
    - description: 'Sharefile System Status page, provided by Citrix'
      group: 3rd Party Status Pages
      link: 'http://status.sharefile.com/'
      name: Sharefile System Status
    - description: Decomissioned 11-18-2019 - replaced with Sharefile
      group: Decomissioned
      name: FTP Server
    - description: Sharefile SaaS Service used to exchange files with clients
      group: File Sharing Services
      link: 'https://ncicap.sharefile.com'
      name: Sharefile Service
    - description: CA Domain Controller
      group: Domain Controllers
      name: DC - CA
    - description: RM Domain Controller
      group: Domain Controllers
      name: DC - RM
    - description: VA Domain Controller
      group: Domain Controllers
      name: DC - VA
    - description: CapNet DB
      group: CapNET Resources
      name: CapNET DB
    - description: CapNET Tools - access via office or VPN
      group: CapNET Resources
      name: CapNET Tools
    - group: CaptionSentry Servers
      name: CA-CS-01
    - group: CaptionSentry Servers
      name: CA-CS-02
    - group: CaptionSentry Servers
      name: CA-CS-03
    - group: CaptionSentry Servers
      name: RM-CS-01
    - group: CaptionSentry Servers
      name: RM-CS-02
    - group: CaptionSentry Servers
      name: RM-CS-03
    - group: CaptionSentry Servers
      name: RM-CS-04
    - group: CaptionSentry Servers
      name: RM-CS-05
    - group: CaptionSentry Servers
      name: RM-CS-06
    - group: CaptionSentry Servers
      name: RM-CS-07
    - group: CaptionSentry Servers
      name: RM-CS-08
    - group: CaptionSentry Servers
      name: VA-CS-01
    - group: CaptionSentry Servers
      name: VA-CS-02
    - group: CaptionSentry Servers
      name: VA-CS-03
    - description: 'Archive Files, Offline'
      group: File Sharing Services
      name: Offline Archives
    - description: VA-RAS server used to provide remote captioners pre-approved public IP
      group: VPN Servers
      name: VPN - RAS
    - description: Asset Tracking System
      group: Management Servers
      name: Lansweeper
    - description: Anti-Virus Console
      group: Management Servers
      name: ESET AV Console
    - description: CA - Network Drives and Network Printer Server
      group: File Sharing Services
      name: CA - File & Print Server
    - description: VA - Network Drives and Network Printer Server
      group: File Sharing Services
      name: VA - File & Print Server
    - description: RM - Network Drives Server
      group: File Sharing Services
      name: RM - File Server
    - description: Report Writer and Scheduler Software
      group: Management Servers
      name: Reports Server
  timezoneString: EST
